services:

  gitea-server:
    image: gitea/gitea:1.23.3
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST:-gitea-db}:${POSTGRES_PORT:-5432}
      - GITEA__database__NAME=${POSTGRES_DB:?POSTGRES_DB not set}
      - GITEA__database__USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - gitea-db
    restart: unless-stopped

  gitea-db:
    image: postgres:14
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB not set}
    volumes:
      - gitea-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  gitea-data:
    driver: local
  gitea-db:
    driver: local
